### ISSUE TITLE
it doesn't "refresh" the names unless you restart vscode

### ISSUE THREAD

**Issue by Vincenzoferrara** [AvaloniaUI/Avalonia.NameGenerator#103]
as the title suggests, the only way to find the changes to the file is to close and reopen vs code (I'm on linux) (vs set to "auto save file")

**Comment by worldbeater** [comment]
Looks like this issue is being tracked at the `omnisharp-vscode` repository: 
https://github.com/OmniSharp/omnisharp-vscode/issues/4215
