### ISSUE TITLE
SourceGenerator seems not working for latest Avalonia Nightly Build

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia.NameGenerator#109]
I'm getting tons of error messages about the ambiguous references:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/25716486/223355112-ad6d3d2c-cc79-444a-b530-c92724748416.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/25716486/223355140-a8e95432-db08-4051-8ecb-e5cf21c0181e.png">

**Comment by MarkusKgit** [comment]
I think its because it now lives in the main repo (at least when you use master/nightly) https://github.com/AvaloniaUI/Avalonia/pull/10407

**Comment by laolarou726** [comment]
> I think its because it now lives in the main repo (at least when you use master/nightly) https://github.com/AvaloniaUI/Avalonia/pull/10407
> 
> 

Now I removed the individual package from my project. How should I enable this source generator again?

**Comment by worldbeater** [comment]
Worth moving this issue to the [main Avalonia repo](https://github.com/avaloniaUI/Avalonia). This repository is going to be archived:

> **Warning** The development of this package has been [**moved**](https://github.com/AvaloniaUI/Avalonia/pull/10407) to the [main AvaloniaUI repository](https://github.com/avaloniaUI/Avalonia). Please consider opening issues or pull requests in the [main AvaloniaUI repository](https://github.com/avaloniaUI/Avalonia). Head over to [AvaloniaUI Gitter](https://gitter.im/AvaloniaUI/Avalonia) or check [AvaloniaUI Discussions](https://github.com/AvaloniaUI/Avalonia/discussions) if you have any questions regarding the migration process.
