### ISSUE TITLE
Remove [GenerateTypedNameReferences] Attribute

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia.NameGenerator#18]
As titled, I think the `[GenerateTypedNameReferences]` C# attribute should be removed as a requirement. It isn't required in WPF/UWP/WinUI.

Simply put, the XAML specifies the class it corresponds with (x:Class). A corresponding partial class should automatically be generated whenever a .xaml or .axaml file contains "x:Name" and certain other XAML attributes. An additional check could involve the .xaml.cs convention if it's required.

**Comment by worldbeater** [comment]
Probably worth implementing this by allowing folks to add a new MSBuild directive `<GenerateTypedNameReferences>true</GenerateTypedNameReferences>` (e.g. if the directive is present, then we don't require the classes to be annotated with the attribute https://github.com/AvaloniaUI/Avalonia.NameGenerator/blob/main/src/Avalonia.NameGenerator/NameReferenceGenerator.cs#L147)

**Comment by robloo** [comment]
An assembly-wide configuration would work. I do think in the future most people will want code generation for this enabled by default. Hopefully all of this ends up in the Avalonia repo itself too.
