### ISSUE TITLE
Feature Filter by namespace

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia.NameGenerator#25]
Since https://github.com/AvaloniaUI/Avalonia.NameGenerator/releases/tag/0.2.0-preview the  the generator processes all  classes inheriting from the Avalonia.INamed interface. 

## Current behavior
 the generator processes all  classes inheriting from the Avalonia.INamed interface. 
## New behavior
When you define `AvaloniaNameGeneratorFilterByNamespace`, the generator only processes classes that inherit from the Avalonia.INamed interface with specified namespaces.

####  It processes all classes with the exact namespace
```xml
<PropertyGroup>
   <AvaloniaNameGeneratorFilterByNamespace>MyApp.Presentation.Views</AvaloniaNameGeneratorFilterByNamespace>
</PropertyGroup>
```
#### It processes all classes with exact namespace and child namespaces
```xml
<PropertyGroup>
   <AvaloniaNameGeneratorFilterByNamespace>MyApp.Presentation.*</AvaloniaNameGeneratorFilterByNamespace>
</PropertyGroup>
```

#### It processes all classes with multiple namespaces
```xml
<PropertyGroup>
   <AvaloniaNameGeneratorFilterByNamespace>MyApp.Presentation.Views;MyApp.Presentation.Controls</AvaloniaNameGeneratorFilterByNamespace>
</PropertyGroup>
```

**Comment by worldbeater** [comment]
Closed by https://github.com/AvaloniaUI/Avalonia.NameGenerator/commit/b00b699e0c6a716b5c126dec29da301836846408, shipped to NuGet as 0.4.1, see also [Advanced Usage](https://github.com/AvaloniaUI/Avalonia.NameGenerator#advanced-usage).
