### ISSUE TITLE
Improve Property Initialization in Generated Code

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/Avalonia.NameGenerator#9]
Ideally, our generated code should use some kind of a lazy initialization to avoid multiple `FindControl<T>` calls. The extensibility point for this should be in the class referenced below. Also, we totally need to somehow unit test this https://github.com/worldbeater/XamlNameReferenceGenerator/blob/main/src/XamlNameReferenceGenerator/NameReferenceGenerator.cs#L120

**Comment by kekekeks** [comment]
Note that generating extra fields is probably a bad idea since those will be visible to the user code. The proper way of control reference initialization would be to generate some kind of a callback that would be used from XAML-compiler generated code (at least that's how WPF does it).

**Comment by worldbeater** [comment]
E.g. this is what the generated code would look like in WPF for a `StackPanel` named `ExampleStackPanel`:

```cs
public partial class DirectAuthView : UserControl, IComponentConnector {
    [DebuggerNonUserCodeAttribute]
    [EditorBrowsableAttribute(EditorBrowsableState.Never)]
    void Connect(int connectionId, object target) { // IComponentConnector implementation
        switch (connectionId)
        {
            case 1:
            this.ExampleStackPanel = (StackPanel)target;
            return;
        }
    }
}
```

**Comment by worldbeater** [comment]
Assuming https://github.com/AvaloniaUI/Avalonia.NameGenerator/pull/29 is merged, we can now turn on initialize component generator behavior as such:
```xml
<PropertyGroup>
  <AvaloniaNameGeneratorDefaultFieldModifier>InitializeComponent</AvaloniaNameGeneratorDefaultFieldModifier>
</PropertyGroup>
```
Probably assigning the controls in the `InitializeComponent` is better than a WPF-like dance with connecting by id etc.
Also worth noting the `InitializeComponent` behavior doesn't seem to be working in Rider yet
https://youtrack.jetbrains.com/issue/RIDER-58080
