### ISSUE TITLE
NameGenerator not working in a UserControl

### ISSUE THREAD

**Issue by joedemax** [AvaloniaUI/Avalonia.NameGenerator#96]
Hi,

In a new Avalonia project, the NameGenerator has been working just fine, however I just added a UserControl and tried to do the following:

`    public ConsoleControl()
    {
        InitializeComponent();
        MyTextBlock.Text = "Test";
    }
`

And I get a NullReferenceException as soon as MyTextBlock.Text is called. Here is the Xaml

`<TextBlock Name="MyTextBlock"></TextBlock>`

What am I doing wrong?

**Comment by worldbeater** [comment]
Hi @joedemax!

Do you have a non-generated `InitializeComponent` method declared in your `UserControl` code-behind file? If so, you need to remove it for the generator to work: https://github.com/AvaloniaUI/Avalonia.NameGenerator#advanced-usage

**Comment by ivanjx** [comment]
maybe put it inside `Loaded` event handler instead of the ctor
